server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: producto-service
              uri: https://proyectoferre-production.up.railway.app
              predicates:
                - Path=/productos/**

            - id: venta-service
              uri: https://radiant-magic-production-58df.up.railway.app
              predicates:
                - Path=/ventas/**